# Generated by Django 4.1.4 on 2023-10-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="votes",
        ),
        migrations.RemoveField(
            model_name="question",
            name="votes",
        ),
        migrations.AlterField(
            model_name="answer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
